const product = [
    {
        name:"Mid Century Modern T-Shirt",
        desc:"Men-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883491/Ecommerce%20Boutique/Images-2_i3ur2j.png",
        price:110,
        countInStock:"10",
    },
    {
        name:"Modern T-Shirt",
        desc:"Men-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883491/Ecommerce%20Boutique/Images-1_rlidcp.png",
        price:139,
        countInStock:"10",
    },
    {
        name:"Corporate Office Shoes",
        desc:"Men-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883492/Ecommerce%20Boutique/Images-12_ilhl3h.png",
        price:399,
        countInStock:"10",
    },
    {
        name:"Black Hoodie",
        desc:"Men-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883492/Ecommerce%20Boutique/Images-5_c3rgtd.png",
        price:110,
        countInStock:"10",
    },
    {
        name:"Green Shoes",
        desc:"Men-Cloths",
        type:"shoe",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883491/Ecommerce%20Boutique/Images-4_fru933.png",
        price:139,
        countInStock:"10",
    },
    {
        name:"White Shoes",
        desc:"Men-Cloths",
        type:"shoe",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883491/Ecommerce%20Boutique/Images-6_ktn6lg.png",
        price:120,
        countInStock:"10",
    },
    {
        name:"Corporate Office Shoes",
        desc:"Men-Cloths",
        type:"shoe",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883493/Ecommerce%20Boutique/Images-9_bxpwbs.png",
        price:399,
        countInStock:"10",
    },
    {
        name:"Modern T-Shirt",
        desc:"Men-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883492/Ecommerce%20Boutique/Images-8_u4ybpo.png",
        price:150,
        countInStock:"10",
    },
    {
        name:"Corporate Office Shoes",
        desc:"Men-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883492/Ecommerce%20Boutique/Images-12_ilhl3h.png",
        price:399,
        countInStock:"10",
    },
    {
        name:"Black Sweeter",
        desc:"Men-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883491/Ecommerce%20Boutique/Images-7_aebasp.png",
        price:110,
        countInStock:"10",
    },
    {
        name:"Lens Combo For Winter",
        desc:"Women-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883490/Ecommerce%20Boutique/Image-3_jtsy2c.png",
        price:150,
        countInStock:"10",
    },
    {
        name:"Office Combo For Gentleman",
        desc:"Men-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883490/Ecommerce%20Boutique/Image_fzdgwi.png",
        price:120,
        countInStock:"10",
    },
    {
        name:"Green Hoodie",
        desc:"Men-Cloths",
        type:"tshirt",
        image:"https://res.cloudinary.com/dvtv1j2rn/image/upload/v1683883489/Ecommerce%20Boutique/Image-13_qverqh.png",
        price:399,
        countInStock:"10",
    },
]
export {
    product
}